### ISSUE TITLE
2 - Code required -  Capital City Report

### ISSUE THREAD

**Issue by djackson001** [carolinemcsherry/SCAD#118]
City Report
A city report requires the following columns:

Name.
Country.
District.
Population.

As a Data Analyst, I need to generate a capital city report containing the following columns: City Name, Country, and Population, to analyse key demographic information of capital cities, facilitate comparison between countries, and support decision-making processes within the organization

select city.Name as Capital ,
country.name as Country, city.Population from city
JOIN country ON country.Code = city.CountryCode
where id in (select country.Capital from country);

**Comment by djackson001** [comment]
For the population reports, the following information is requested:

The name of the continent/region/country.
The total population of the continent/region/country.
The total population of the continent/region/country living in cities (including a %).
The total population of the continent/region/country not living in cities (including a %).

**Comment by Antonia2206** [comment]
select country.name,
sum(country.Population) as Total_Country_Population,
SUM(city.Population) as Total_City_Population,
CONCAT(round(SUM(city.Population) / SUM(country.Population) * 100, 2),'%') as City_Population_Percentage,
SUM(country.Population)-SUM(city.Population) as Total_Not_City_Population,
CONCAT(100 - round(SUM(city.Population) / SUM(country.Population) * 100, 2) ,'%') as None_City_Population_Percentage
from country
JOIN city ON country.Code = city.CountryCode
group by country.name;

SELECT country.Continent, sum(country.Population) as Total_Continent_Population,
SUM(city.Population) as Total_City_Population,
CONCAT(round(SUM(city.Population) / SUM(country.Population) * 100, 2),'%') as City_Population_Percentage,
SUM(country.Population)-SUM(city.Population) as Total_Not_City_Population,
CONCAT(100 - round(SUM(city.Population) / SUM(country.Population) * 100, 2) ,'%') as None_City_Population_Percentage
from country
JOIN city ON country.Code = city.CountryCode
GROUP BY country.Continent;

SELECT country.Region, sum(country.Population) as Total_Region_Population,
SUM(city.Population) as Total_City_Population,
CONCAT(round(SUM(city.Population) / SUM(country.Population) * 100, 2),'%') as City_Population_Percentage,
SUM(country.Population)-SUM(city.Population) as Total_Not_City_Population,
CONCAT(100 - round(SUM(city.Population) / SUM(country.Population) * 100, 2) ,'%') as None_City_Population_Percentage
from country
JOIN city ON country.Code = city.CountryCode
GROUP BY country.Region;
