### ISSUE TITLE
17 - Code Required - the top N populated cities within a district, where N is determined based on planning requirement

### ISSUE THREAD

**Issue by Antonia2206** [carolinemcsherry/SCAD#134]
•	17.The top N populated cities in a district where N is provided by the user.

As a City Planner, I require access to the top N populated cities within a district, where N is determined based on planning requirements, to assess urban growth, prioritize infrastructure projects, and develop sustainable development plans tailored to the demographic needs of the district's population.

SELECT population, name AS CityName, District
FROM city;

**Comment by djackson001** [comment]
String strSelect = "SELECT Name AS CityName, District, Population " +
                    "FROM city " +
                    "WHERE District = '" + district + "' " +
                    "ORDER BY Population DESC " +
                    "LIMIT " + limit;
