### ISSUE TITLE
User story 26 - As a data analyst, I need the functionality to retrieve the top N populated countries in the world, where N is provided by me, to conduct demographic analysis efficiently.

### ISSUE THREAD

**Issue by djackson001** [carolinemcsherry/SCAD#60]
tasks to complete
Connect to the existing database.
Add function to retrieve data on country's in world 
Add function to retrieve data on population
Generate report

**Comment by carolinemcsherry** [comment]
User story 26
 The top N populated countries in the world where N is provided by the user.

select * 
from country
order by country.Population desc
limit 5; #This will be user defind var;
