### ISSUE TITLE
user story 24 - As a Geographer, I require a feature that allows me to explore cities within a specific continent, sorted by population from largest to smallest, to study regional population trends and urban development patterns

### ISSUE THREAD

**Issue by djackson001** [carolinemcsherry/SCAD#62]
tasks to complete
Connect to the existing database.
Add function to retrieve data on continent
Add function to retrieve data on cities
Generate report

**Comment by carolinemcsherry** [comment]
user story 24
 All the cities in a continent organised by largest population to smallest

select country.Continent, 
country.Name as 'County Name', 
city.Name as 'City Name', 
city.District, 
city.Population as 'Population descending'
from city
JOIN country ON country.Code = city.CountryCode # joining the table country to countrylanguage
where country.Continent = 'Asia'  #This will be user defind var
order by city.Population desc;
