### ISSUE TITLE
User story 23 - As an Urban Planner, I need to analyse cities within a particular region, sorted by population from largest to smallest, to make informed decisions regarding infrastructure development, resource allocation, and city planning initiatives

### ISSUE THREAD

**Issue by djackson001** [carolinemcsherry/SCAD#63]
tasks to complete
Connect to the existing database.
Add function to retrieve data on region 
Add function to retrieve data on cities
Generate report

**Comment by carolinemcsherry** [comment]
User Story  23
 All the cities in a region organised by largest population to smallest.

select 
city.Name as 'City Name', 
city.District, 
city.Population as 'Population descending'
from city
JOIN country ON country.Code = city.CountryCode # joining the table country to countrylanguage
where country.Region = 'Caribbean' #This will be user defind var
order by city.Population desc;
