### ISSUE TITLE
User Story 21 - As a City Administrator, I need to view all cities within my district, sorted by population from largest to smallest, to monitor population dynamics, plan public services, and address urbanization challenges effectively.

### ISSUE THREAD

**Issue by djackson001** [carolinemcsherry/SCAD#65]
**tasks to complete**
Connect to the existing database.
Add function to retrieve data on population
Add function to retrieve data on Cities
Generate report

**Comment by carolinemcsherry** [comment]
User Story 21
All the cities in a district organised by largest population to smallest.

select * from city 
where city.District = 'Zytomyr' #This will be user defind var
order by city.Population desc;
