### ISSUE TITLE
User story 19- As a Demographer, I require access to the top N populated cities within a continent, with N determined by my analysis requirements, to study population dynamics, migration patterns, and cultural diversity across different continents for academic or policy research purposes

### ISSUE THREAD

**Issue by djackson001** [carolinemcsherry/SCAD#67]
**tasks to complete**
Connect to the existing database.
Add function to retrieve data on population
Add function to retrieve data on cities
Add function to retrieve data on continents
Generate report

**Comment by carolinemcsherry** [comment]
User story 19
 The top N populated cities in a continent where N is provided by the user.

select country.Name, city.Name, city.District, city.Population 
from city
JOIN country ON city.CountryCode = country.Code  
where city.CountryCode in 
(select code
from country
where country.Continent = 'North America') #This will be user defind var
order by city.Population desc
limit 5; #This will be user defind var
