### ISSUE TITLE
User Story 18 - As a Market Analyst, I need to identify and analyse the top N populated cities within a specific country, where N is specified by me, to evaluate market potential, understand consumer behaviour, and develop targeted marketing strategies for products or services in various urban markets.

### ISSUE THREAD

**Issue by djackson001** [carolinemcsherry/SCAD#68]
**tasks to complete**
Connect to the existing database.
Add function to retrieve data on population
Add function to retrieve data on countries
Add function to retrieve data on cities
Generate report

**Comment by Antonia2206** [comment]
select
A. Name as cityname,
B. Name as countryname,
A. Population
from city A
left join country B on A. CountryCode = B. Code;
