### ISSUE TITLE
user story 5 - As a Linguistic Data Analyst, I need access to comprehensive data on the number of people who speak various languages worldwide, sorted from greatest to smallest, along with the percentage of the world population speaking each language, to conduct in-depth linguistic analysis, identify language trends, and inform decision-making processes related to language education, cultural diversity, and international communication strategies within the organization

### ISSUE THREAD

**Issue by djackson001** [carolinemcsherry/SCAD#81]
**tasks to complete**
Connect to the existing database.
Add function to retrieve data on population
Add function to retrieve data on spoken languages 
Generate report

**Comment by carolinemcsherry** [comment]
# user story 5 number of people who speak Chinese.
# English.
# Hindi.
# Spanish.
# Arabic.
#  from greatest number to smallest, including the percentage of the world population


SELECT countrylanguage.Language, 
SUM(ROUND(countrylanguage.Percentage / 100 * country.Population)) AS speakers_world_wide,
CONCAT(round((SUM(ROUND(countrylanguage.Percentage / 100 * country.Population)) / (SELECT SUM(Population) FROM country)) * 100,2), '%') AS '% of speakers world wide'
FROM countrylanguage
JOIN country ON country.Code = countrylanguage.CountryCode # joining the table country to countrylanguage
WHERE countrylanguage.Language IN ('Chinese', 'English', 'Hindi', 'Spanish', 'Arabic') #  specafiling the 5 asked for languages 
GROUP BY countrylanguage.Language
ORDER BY speakers_world_wide DESC; # this is ordering the from greatest number to smallest
