### ISSUE TITLE
User story 4 - As a Report Generator, I need a feature to generate a country report containing the following columns: Country Code, Country Name, Continent, Region, Population, and Per Capita Income, to compile comprehensive country-level data for analysis, decision-making, and reporting purposes within the organization

### ISSUE THREAD

**Issue by djackson001** [carolinemcsherry/SCAD#82]
tasks to complete 
Connect to the existing database.
Add function retrieve population data
Add function retrieve County code data
Add function retrieve country name data
Add function retrieve continent  data
Add function retrieve per capita income data
Generate report

**Comment by Antonia2206** [comment]
select 
Code, Name, Continent, Region, Population, GNP
 from country
