### ISSUE TITLE
User story 3 - As a Report Compiler, I require a functionality to generate a city report including the following columns: City Name, Country, District, and Population, to compile detailed city-level data for analysis, decision-making, and reporting purposes within the organization

### ISSUE THREAD

**Issue by djackson001** [carolinemcsherry/SCAD#83]
**tasks to complete**
Connect to the existing database.
Add function to retrieve data on population
Add function to retrieve data on countries
Add function to retrieve data on city name
Add function to retrieve data on Districts 
Generate report

**Comment by Antonia2206** [comment]
select 
A. Name as cityname, 
B. Name as countryname,
A. District,
A. Population
from city A
left join country B on A. CountryCode = B. Code
