### ISSUE TITLE
User Story 2 - As a Data Analyst, I need to generate a capital city report containing the following columns: City Name, Country, and Population, to analyse key demographic information of capital cities, facilitate comparison between countries, and support decision-making processes within the organization

### ISSUE THREAD

**Issue by djackson001** [carolinemcsherry/SCAD#84]
**tasks to complete**
Connect to the existing database.
Add function to retrieve data on population
Add function to retrieve data on countries
Add function to retrieve data on City name 
Generate report

**Comment by carolinemcsherry** [comment]
select city.Name as Capital , 
country.name as Country, city.Population  from city
JOIN country ON country.Code = city.CountryCode
where id in (select country.Capital from country);
